### ISSUE TITLE
Bug: When Insert frame is opened new Insert clicks reload that frame in old position

### ISSUE THREAD

**Issue by agsagds** [deep-foundation/deepcase-app#100]
I found bug into placement behavior: If InsertCard frame still opened, new Insert command not moved this onto click position. 
That conditioned permanent undefinite state of "cy" variable ( _see imports/cyto/hooks.tsx line 199 for details_ ).

**Frist:** open Insert menu here
![изображение](https://user-images.githubusercontent.com/4994868/232127862-9e415414-bedb-4b56-b02e-6667df84e2d2.png)
**Second:** want to reopen Inser menu here
![изображение](https://user-images.githubusercontent.com/4994868/232127996-b8df49df-1256-439d-a50e-75ec48d8aff6.png)
**Third:** menu reloaded at first position instead of new position
![изображение](https://user-images.githubusercontent.com/4994868/232128166-49b9c05a-630f-4479-8b0f-80fdece50c05.png)

**Comment by agsagds** [comment]
@FreePhoenix888 please, mark this as bug and change state to "In Process"

**Comment by konard** [comment]
5000 rub reward is paid
