### ISSUE TITLE
Center menu does not center links, but puts them into left upper corner

### ISSUE THREAD

**Issue by konard** [deep-foundation/deepcase-app#119]
![59A7122E-7E1C-42DB-AFF2-529E167AFC78](https://user-images.githubusercontent.com/1431904/232611068-f8562e44-981e-4c97-a95a-1bd6ec22ab4b.png)

**Comment by FreePhoenix888** [comment]
Fixed in https://github.com/deep-foundation/deepcase-app/commit/347db4c491bd57d442004fb2781d8fb710bb3483

**Comment by konard** [comment]
![IMG_0884](https://user-images.githubusercontent.com/1431904/236639325-7de7fe50-50f8-4042-857f-d7ffbbe05c41.png)

We should also fix center on startup of deepcase to close this issue.

**Comment by FreePhoenix888** [comment]
https://chat.openai.com/share/8d98842f-d802-4d26-b406-2f4a880a32c3
@FreePhoenix888

**Comment by konard** [comment]
Done at https://github.com/deep-foundation/deepcase/commit/170c45980e77d9f27a0e8a60fd64eeec774f4937
