### ISSUE TITLE
Open handler in editor when using handlers menu

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deepcase-app#132]
# Actual
We just see ids of handles, handlers in handlers menu

# Expected
We are able to click on id of handler and it will be opened in the editor

# Additional Information
When I say handlers menu I mean this menu located on the right side of editor (Handlers menu should be selected in the right bottom menu)
![image](https://user-images.githubusercontent.com/66206278/235601709-f1d6902b-884c-4a05-b0f4-8e0001e963a1.png)

**Comment by Aruseli** [comment]
commit https://github.com/deep-foundation/deepcase/commit/7535c681e9373597e38b41a64f7450c7e32eb7f8
