### ISSUE TITLE
When installing the parent package failed, the dependencies packages that were installed were not removed

### ISSUE THREAD

**Issue by suenot** [deep-foundation/deepcase-app#169]
- Install package @deep-foundation/deep-memo v 0.0.11 with @deep-foundation/npm-packager-ui v0.0.8 with error:
![image](https://github.com/deep-foundation/deepcase/assets/1426876/64608427-8d44-4514-81c9-bb56295413a2)
```
{
  "stack": "Error: Package version is not synchronized between deep.json and package.json files.\n  deep.json package version: 4.0.12.\n  package.json package version: 4.0.13.\n    at deepImport (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:59:13)\n    at eval (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:236:40)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "message": "Package version is not synchronized between deep.json and package.json files.\n  deep.json package version: 4.0.12.\n  package.json package version: 4.0.13."
}
```
- And I found that I had successfully installed some packages, that are in dependency of @deep-foundation/deep-memo:
![image](https://github.com/deep-foundation/deepcase/assets/1426876/118bd70c-6167-4794-94b7-42c7632d860c)

Is it the correct expected behavior?

**Comment by konard** [comment]
https://discord.com/channels/739430470345031692/1095252006077202472/1118611087324098621

**Comment by suenot** [comment]
I close this question, because I forget that I install @deep-foundation/capacitor-device that can have in dependencies: @deepfoundation/capacitor-haptics and @deep-foundation/capacitor-screen-reader.
