### ISSUE TITLE
Name for type 5 is not displayed in the package.

### ISSUE THREAD

**Issue by konard** [deep-foundation/deepcase-app#189]
### Describe the bug

![Screenshot_20230711_115106](https://github.com/deep-foundation/deepcase/assets/1431904/43f1e8a3-157f-440b-80ed-fe2c3f6ce7a0)

### Expected Behavior

Name for type 5 is displayed in the package.

### Current Behavior

Name for type 5 is not displayed in the package.

### To Reproduce

1. Install @deep-foundation/capacitor-device
2. Go to package as space
3. Look at type with id 5
...

**Comment by FreePhoenix888** [comment]
Copy of https://github.com/deep-foundation/deepcase/issues/174 ?

**Comment by konard** [comment]
Duplicate of https://github.com/deep-foundation/deepcase/issues/174
