### ISSUE TITLE
Empty page after login as admin

### ISSUE THREAD

**Issue by konard** [deep-foundation/deepcase-app#236]
![IMG_1686](https://github.com/deep-foundation/deepcase-app/assets/1431904/6342ad2d-7cd5-42ad-a15f-2d4269ed2199)

# Workaround

Reload the page

**Comment by PavelBandal** [comment]
Пример бага

https://github.com/deep-foundation/deepcase-app/assets/32432734/b881f835-505d-40f7-b99a-424363c94ff5

**Comment by konard** [comment]
# Workaround 1

Switch `deeplinks` submodule/repository to 0.0.302 tag.

That means the problem is somewhere here:
https://github.com/deep-foundation/deeplinks/compare/0.0.302...main
