### ISSUE TITLE
Default browser context menu is opened when using `Insert` button from deep context menu opened by right mouse button click

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deepcase-app#57]
![image](https://user-images.githubusercontent.com/66206278/214803440-4583b008-75bd-47f7-b876-b6f52d11a22a.png)
![image](https://user-images.githubusercontent.com/66206278/214803482-5fce8158-d935-4433-83ae-2eed19227b52.png)

**Comment by agsagds** [comment]
@FreePhoenix888 can u set labels for this issue?

**Comment by FreePhoenix888** [comment]
> @FreePhoenix888 can u set labels for this issue?

Done

**Comment by agsagds** [comment]
> > @FreePhoenix888 can u set labels for this issue?
> 
> Done

And status "In progress". I get it in work

**Comment by FreePhoenix888** [comment]
> > > @FreePhoenix888 can u set labels for this issue?
> > 
> > Done
> 
> And status "In progress". I get it in work

Done

**Comment by agsagds** [comment]
@FreePhoenix888 fix changes https://github.com/deep-foundation/deepcase/pull/97 accepted. Issue ready to close.
