### ISSUE TITLE
install button position is broken and it is not clickable in npm-packager-ui

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deepcase-app#77]
![image](https://user-images.githubusercontent.com/66206278/228256613-2a508072-cb30-4bb8-be1f-519c43a68b36.png)

**Comment by konard** [comment]
Once we add description to the package we get the same problem to each package:
![C9BC2B5F-EF03-4737-B66B-A0893DBC0183](https://user-images.githubusercontent.com/1431904/228861702-bf62cdee-169e-4fa1-9549-90313e3e3ec2.png)
