### ISSUE TITLE
stringHandler is unreadable in white/light theme

### ISSUE THREAD

**Issue by konard** [deep-foundation/deepcase-app#80]
![Screenshot_20230328_175823](https://user-images.githubusercontent.com/1431904/228280264-30e54826-f02c-4b62-bb10-52bc6392903b.png)

**Comment by CEHR2005** [comment]
Как воспроизвести? 
<img width="314" alt="image" src="https://user-images.githubusercontent.com/8792220/232169901-95d55e7b-e5c1-48ca-bd7d-506102e0449f.png">
По крайне мере сейчас при белой теме все вполне читаемо

**Comment by konard** [comment]
This issue was fixed.
