### ISSUE TITLE
Proposal: add checkbox to hide red markers

### ISSUE THREAD

**Issue by suenot** [deep-foundation/deepcase-app#94]
![image](https://user-images.githubusercontent.com/1426876/230659046-a394b479-d852-40e7-975a-163cc4a4b579.png)

**Comment by suenot** [comment]
Another example of heap of links:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/1426876/231272983-8dd0e10c-1a03-483c-916c-2d598392df78.png">

**Comment by konard** [comment]
This is duplicate of https://github.com/deep-foundation/deepcase/issues/92
